version: '3'
services:

  redis-master:
    build: ./code/redisMaster
    image: redis:master
    container_name: redis-master

  redis-slave1:
    build: ./code/redisSlave
    image: redis:slave
    container_name: redis-slave1
    depends_on:
      - redis-master
    links:
      - redis-master:master

  
  redis-slave2:
    build: ./code/redisSlave
    image: redis:slave
    container_name: redis-slave2
    depends_on:
      - redis-master
    links:
      - redis-master:master
   

  app:
    build: ./code/app
    image: django:app
    container_name: app
    volumes:
      - "./code/app/redisweb:/usr/src/app"
    depends_on:
      - redis-master
    links:
      - redis-master:db
    command: python manage.py runserver 0.0.0.0:8000

  app1:
    build: ./code/app1
    image: django:app1
    container_name: app1
    volumes:
      - "./code/app1/django-cms:/usr/src/app"
    command: python manage.py runserver 0.0.0.0:8001

  HAProxy:
    build: ./code/HAProxy
    image: haproxy:HAProxy
    container_name: HAProxy
    depends_on:
      - app
      - app1
    links:
      - app:app
      - app1:app1
    ports:
      - "6300:6300"
      - "6301:6301"
    command: haproxy -f haproxy.cfg

     
